const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';
const INITIAL_UPDATE_STATE = 'INITIAL_UPDATE_STATE';
export const todoActionType = {
  ADD_TODO,
  DELETE_TODO,
  TOGGLE_TODO,
  INITIAL_UPDATE_STATE,
};
